### ISSUE TITLE
SmarPod scanning issues

### ISSUE THREAD

**Issue by klauer** [NSLS-II-HXN/ipython_ophyd#1]
Scanning multiple SmarPod axes (e.g., in a `mesh` scan) fails due to bluesky's `set` and `wait_on_group` style of motion commands.

Best would be to fix it on the IOC level such that multiple motion requests all return motion complete properly.

Simple immediate fix could be:
- Move axes individually in the scan plans

Post ophyd refactor
- A PseudoPositioner should take care of this - set all setpoints and then move()

Hanfei indicated this could be worked around in the short term, so leaving it open as-is.

**Comment by jklynch** [comment]
closing as stale, HXN staff report they do not see this issue anymore.
